### ISSUE TITLE
Cannot create references to elements of a temporary array expression

### ISSUE THREAD

**Issue by lutek** [DonatasL/PrestaShop-ElasticSearch#3] opened 2015-09-04 15:00 UTC
Hi,

I tried install module and got error just after upload module:
[PrestaShop] Fatal error in module file :/srv/www/fw/ps16fw.local/modules/elasticsearch/elasticsearch.php:
Cannot create references to elements of a temporary array expression

when accessing module section:
[PrestaShop] Fatal error in module file :/srv/www/fw/ps16fw.local/classes/module/Module.php(1238) : eval()'d code:
Cannot create references to elements of a temporary array expression

Prestashop 1.6.0.11
PHP 5.4.43-1~dotdeb+7.1

**Comment by DonatasL** [comment] 2015-09-04 15:26
Hi,
our module is not stable yet and we are making big changes in source code. Next version will be released after 1-2 months.

**Comment by DonatasL** [comment] 2015-09-04 15:28
The issue is because of this:
http://stackoverflow.com/questions/24772958/is-there-a-rational-explanation-for-this-php-call-by-value-behavior-or-php-bug

It's ok with 5.5 version.

I strongly suggest wait till more stable version of this module will be released.

**Comment by lutek** [comment] 2015-09-04 15:56
Thanks. Found the same info about php 5.5
Testing locally module.
Great idea i have just thought about better search for prestashop. I hope i can be helpfully

**Comment by DonatasL** [comment] 2015-09-04 16:12
Np!
Thanks for testing :)
I'm closing this issue this then.

**Closed by DonatasL** 2015-09-04 16:12 UTC
